version: "3"
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www/html
    environment:
    
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 9000:9000
    networks:
      - nginxphp
  web:
    image: nginx:latest

    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginxphp
    depends_on:
      - php
  mysql:
    image: mysql:8.0.0
    ports:
      - 4306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - php
    networks:
      - nginxphp
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - nginxphp

networks:
  nginxphp:
